### PR TITLE
Issue 24

### PR DESCRIPTION
**Pull request by koheiw**
Allow passing a dense matrix to `x` or `y` for #24.

### CODE REVIEW

**Comment by koheiw** [comment]
It is failing the tests on Ububtu 18 devel only because of 
```
Run rcmdcheck::rcmdcheck(args = c("--no-manual", "--as-cran"), error_on = "warning", check_dir = "check")
Error: Error in loadNamespace(x) : there is no package called ‘rcmdcheck’
Calls: loadNamespace -> withRestarts -> withOneRestart -> doWithOneRestart
Execution halted
Error: Process completed with exit code 1.
```

**Comment by kasperwelbers** [comment]
Hi @koheiw,

Is this a check on submitting to CRAN, or is this via the github workflow? I haven't worked with github workflows in R packages yet (but it seems pretty cool!). 

Just by eyeballing the yaml, wouldn't it simply be a matter of adding install.packages('rcmdcheck') on line 71 before using it? 

Or am I completely misunderstanding the issue?

**Comment by kasperwelbers** [comment]
Oh no, wait. It does try to install rcmdcheck, but fails when installing curl

Issue might be that libcurl4-openssl-dev is not installed. That also explains why it only fails on Ubuntu dev. I suppose this could be hacked into the yaml as well, but it seems this yaml is auto-generated, right?

**Comment by koheiw** [comment]
Hi @kasperwelbers the check is on Github Action, a new CI platform. The test environment are all defined in the yaml file, but I am using common template. 

I thought libcurl4-openssl-dev could be the issue, but the yaml file for the rcmdcheck package dosen't have anything related:

https://github.com/r-lib/rcmdcheck/blob/master/.github/workflows/check-pak.yaml

It could be a temporary issue in the development version of R...

**Comment by koheiw** [comment]
YAML file from https://github.com/r-lib/actions/blob/master/examples/test-coverage.yaml fixed the problem! It actually does not test on very old Ubuntu 18.

**Comment by koheiw** [comment]
@kasperwelbers, can you review? My PR passed all the checks.

**Review by kasperwelbers — APPROVED** [review]
Cool, did you actually just customize the yaml, or is this due to an update?

Anyway, looks good!

**Comment by koheiw** [comment]
I only updated the test setting the in YAML file, so no change in package itself. Thank you for reviewing. I will submit to CRAN soon.

**Pull request merged**
