### PR TITLE
Add sparse = TRUE

### PR DESCRIPTION
**Pull request by koheiw**
Add `sparse = TRUE`. This is a new branch for #38.

### CODE REVIEW

**Comment by koheiw** [comment]
```
> require(Matrix)
> mat <- rsparsematrix(1000, 10, 0.5)
> 
> print(object.size(dist(mat, sparse = TRUE)), unit = "Mb")
7.6 Mb
> print(object.size(dist(mat, sparse = FALSE)), unit = "Mb")
3.8 Mb
> 
> microbenchmark::microbenchmark(
+     dist(mat, sparse = TRUE),
+     dist(mat, sparse = FALSE),
+ times = 10)
Unit: milliseconds
                      expr     min      lq     mean  median      uq     max neval
  dist(mat, sparse = TRUE) 26.4083 26.6380 26.89330 26.8313 27.1955 27.6437    10
 dist(mat, sparse = FALSE) 25.3591 25.8587 27.59053 26.1021 26.3652 41.3386    10
```

**Comment by koheiw** [comment]
@rcannood can you review?

**Review by rcannood — APPROVED** [review]
Implementation looks good -- though this was to be expected since you also added unit tests ;)

Revdepcheck succeeds!

    > revdepcheck::revdep_check(num_workers = 30, timeout=as.difftime(60, units = "mins"))
    ── INIT ────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────── Computing revdeps ──
    ── INSTALL ────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────── 2 versions ──
    Installing CRAN version of proxyC
    also installing the dependencies ‘Rcpp’, ‘RcppArmadillo’
    
    Installing DEV version of proxyC
    Installing 2 packages: Rcpp, RcppArmadillo
    ── CHECK ─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────── 12 packages ──
    ✔ dynutils 1.0.11                        ── E: 1     | W: 0     | N: 0                                                                                                              
    ✔ LSX 1.4.0                              ── E: 0     | W: 0     | N: 1                                                                                                              
    ✔ applicable 0.1.0                       ── E: 1     | W: 0     | N: 0                                                                                                              
    ✔ quanteda.textstats 0.97                ── E: 0     | W: 0     | N: 0                                                                                                              
    ✔ immcp 1.0.3                            ── E: 0     | W: 0     | N: 0                                                                                                              
    ✔ SimBu 1.4.3                            ── E: 0     | W: 0     | N: 2                                                                                                              
    ✔ seededlda 1.2.1                        ── E: 0     | W: 0     | N: 4                                                                                                              
    ✔ scClassify 1.14.0                      ── E: 0     | W: 0     | N: 0                                                                                                              
    ✔ simona 1.0.10                          ── E: 0     | W: 1     | N: 2                                                                                                              
    ✔ scFeatures 1.3.2                       ── E: 0     | W: 1     | N: 2                                                                                                              
    ✔ simplifyEnrichment 1.12.0              ── E: 0     | W: 0     | N: 1                                                                                                              
    ✔ scMerge 1.18.0                         ── E: 3     | W: 0     | N: 0                                                                                                              
    OK: 12                                                                                                                                                                            
    BROKEN: 0
    Total time: 35 min

**Comment by koheiw** [comment]
@rcannood thank you!

**Pull request merged**
