### PR TITLE
Add smooth2

### PR DESCRIPTION
**Pull request by koheiw**
For the issue #8, I added the smooth argument. I also corrected how Chi2 and Kullback divergence scores are computed. They match the entropy package's output now. Do you think I have to add smooth to other measures like Canberra?

### CODE REVIEW

**Comment by koheiw** [comment]
@kasperwelbers, do you have comments on smoothing?

**Comment by kasperwelbers** [comment]
@koheiw, no comments really, I think this approach works well. I'm not an expert on smoothing, but every now and then I read up on smoothing in the hopes of finding something better than laplace / add-delta smoothing, and I never found strong evidence that a more sophisticated approach works better (for unigram smoothing).

**Comment by koheiw** [comment]
@kasperwelbers thanks. Do you want to add smoothing to other measures than Chi-squared and Kullback?

**Comment by kasperwelbers** [comment]
@koheiw I don't think I would suggest that. I suppose the argument would be that it makes sense to the user if smoothing was an option for every measure, but it would also make things confusing, as you'd have to explain why they can but probably shouldn't smooth for things like cosine similarity.

I don't think there is a strong benefit of using smoothing for dot product based measures. But I do see a strong downside. I haven't though this through carefully, but I suppose it would mean that the resulting adjacency matrix would always be completely dense (If no term value is zero, every document pair has non-zero similarity).

**Comment by koheiw** [comment]
It is easy to make smoothing possible in all the pariwise methods, but it does not make sense for set-theory based or spatial similarity/distance. Chis-squared and Kullback are difference compares distributions as you know. [Canberra](https://en.wikipedia.org/wiki/Canberra_distance) seems to be a spatial measure.

Results would be dense but it is not a problem becasue users can till sparsify them using`min_simil` or `rank`.

**Comment by kasperwelbers** [comment]
Right, I think that distinction makes sense. You just need smoothing if the vectors represent probability distributions.

The dense results indeed wouldn't be a problem with some pruning, but users might not want to use a threshold if they don't need to. So then smoothing would just create an extra reason to use a threshold.

**Comment by koheiw** [comment]
Seems that we are good already if my classification is correct.
- Spatial
  - euclidean
  - cosine
  - manhattan
  - canberra
  - minkowski
- Set-theory
  - jaccard
  - ejaccard
  - dice
  - edice
  - hamman
  - simple matching
  - faith
- Distribution
  - chisquared (already has smoothing)
  - correlation (smoothing has no effect)
  - kullback (already has smoothing)
  - maximum (smoothing has no effect)

**Comment by rcannood** [comment]
Hey all! I'll review these changes on Wednesday, would that be ok?

**Comment by koheiw** [comment]
@rcannood it would be great if you could review this PR and merge before I update the CRAN version. I addressed major bugs recently.

**Review by rcannood — APPROVED** [review]
My bad, I apologise for the delay :bow: .

I went over the smoothing-related changes, and everything looks ok! :ok_hand: 

[c00f33b]: Related to this commit, can we not simply add hamming to the package? For example, something like this.

```c++
double dist_hamming(colvec& col_i, colvec& col_j) {
    return accu(col_i != col_j);
}
```

If desired, I can add this (with unit test) in a separate PR.

**Comment by koheiw** [comment]
Thank you for taking your time @rcannood. It would be fantastic to add hamming! The [algorithm](https://en.wikipedia.org/wiki/Hamming_distance) looks super simple.

Let me merge this PR.

**Pull request merged**
